### PR TITLE
fix(kit): `Number` fails to trim leading zeroes after deleting of leading digit

### LINKED ISSUE #266: 🐞 - `Number` fails to trim leading zeroes after deleting of leading digit
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://tinkoff.github.io/maskito/kit/number/API?thousandSeparator=_&precision=2

### Description

1. Open https://tinkoff.github.io/maskito/kit/number/API?thousandSeparator=_&precision=2
2. Type `1000000` (million)
3. Move caret after the first digit (`1|_000_000`)
4. Press Backspace

**Expected behaviour:** `0`
Actual behaviour: `0_000`

### Maskito version

0.9.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by nsbarsukov**
## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #266

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

File: projects/kit/src/lib/masks/number/processors/leading-zeroes-validation-postprocessor.ts [hunk 1]
```diff
@@ -9,7 +11,33 @@ import {MaskitoOptions} from '@maskito/core';
...
+                // all leading zeroes followed by another zero
+                new RegExp(`^(\\D+)?[0${escapeRegExp(thousandSeparator)}]+(?=0)`),
+                '$1',
+            )
+            .replace(
+                // zero followed by not-zero digit
+                new RegExp(`^(\\D+)?[0${escapeRegExp(thousandSeparator)}]+(?=[1-9])`),
+                '$1',
+            );
+    };
```
Comment (splincode) [inline projects/kit/src/lib/masks/number/processors/leading-zeroes-validation-postprocessor.ts:28]:
```ts
const escaped = escapeRegExp(thousandSeparator);

return value
            .replace(
                // all leading zeroes followed by another zero
                new RegExp(`^(\\D+)?[0${escaped}]+(?=0)`),
                '$1',
            )
            .replace(
                // zero followed by not-zero digit
                new RegExp(`^(\\D+)?[0${escaped}]+(?=[1-9])`),
                '$1',
            );

```

Comment (nsbarsukov) [reply projects/kit/src/lib/masks/number/processors/leading-zeroes-validation-postprocessor.ts]: fixed
